version: "3.1"

services:
  myjenkins:
    build:
      context: ./myjenkins
      network: host
    image: myjenkins
    ports:
     - "8080:8080"
    # depends_on:
    #  - mysonar
    #  - artifactory
    # links:
    #   - mysonar
    #   - artifactory
    volumes:
     - "./myjenkins/jobs:/var/jenkins_home/jobs/"
     - "./myjenkins/m2deps:/var/jenkins_home/.m2/repository/"
     - "./myjenkins/downloads:/var/jenkins_home/downloads"
    secrets:
     - artifactoryPassword

  filebeat:
    image: elastic/filebeat:6.0.0
    volumes:
      - "./myjenkins/jobs:/var/jenkins_home/jobs/"
      - "./filebeat/logs:/var/log/filebeat"
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"
    depends_on:
      - myjenkins

  # mysonar:
  #   image: sonarqube:6.3.1
  #   ports:
  #    - "9000:9000"

  # artifactory:
  #   image: docker.bintray.io/jfrog/artifactory-oss:5.4.4
  #   ports:
  #    - "8081:8081"

  logstash:
    image: logstash:5.0.0
    volumes:
          - ./logstash/config:/usr/share/logstash/config
    command: logstash -f /usr/share/logstash/config/logstash.conf
    links:
     - elasticsearch
    depends_on:
     - elasticsearch

  elasticsearch:
     image: elasticsearch:5.0.0
     ports:
      - "9200:9200"

  kibana:
    image: kibana:5.0.0
    ports:
     - "5601:5601"
    links:
     - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
     - elasticsearch

secrets:
  artifactoryPassword:
    file: ./myjenkins/secrets/artifactoryPassword

networks:
  default:
    driver: bridge

